//! Terminal engine adapter (ADR-0001): the narrow seam between oly and the
//! embedded terminal core (`alacritty_terminal` 0.26).
//!
//! The rest of the codebase must not depend on engine types directly —
//! session state, snapshots, mode tracking, and query answering all go
//! through [`Terminal`]. The engine owns terminal semantics; oly owns
//! ordering (one feed per journal-sequenced chunk, under the session write
//! lock), policy (which queries may be answered), and persistence.
//!
//! Query responses are generated by the engine *while* a chunk advances,
//! i.e. at the exact stream position of each query (invariant I5) — a
//! chunk containing `A`, CPR, `B`, CPR yields two responses with two
//! distinct cursor positions, by construction.

use std::collections::VecDeque;
use std::sync::{Arc, Mutex};

use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::Dimensions;
use alacritty_terminal::index::Line;
use alacritty_terminal::term::{Config, Term, TermMode, test::TermSize};
use alacritty_terminal::vte::ansi::Processor;

/// Events the engine raised while feeding one chunk, in stream order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineEvent {
    /// Bytes the terminal asks to be written back to the PTY (query
    /// response: CPR/DSR/DA/DECRQM/…). Generated at the query's exact
    /// position in the stream; writing them in drain order preserves it.
    Respond(Vec<u8>),
    /// Window title set (OSC 0/2) or reset to default (`None`).
    Title(Option<String>),
    /// BEL received.
    Bell,
}

/// Terminal modes oly's input translation and attach relays track.
// The M2-2 runtime integration constructs this outside tests.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct EngineModes {
    pub app_cursor_keys: bool,
    pub bracketed_paste: bool,
    pub alt_screen: bool,
}

/// Listener handed to `Term`; events fired during `advance` are queued and
/// drained by the adapter after the feed returns.
#[derive(Clone, Default)]
struct QueueListener {
    events: Arc<Mutex<VecDeque<EngineEvent>>>,
}

impl EventListener for QueueListener {
    fn send_event(&self, event: Event) {
        let mapped = match event {
            Event::PtyWrite(text) => Some(EngineEvent::Respond(text.into_bytes())),
            Event::Title(title) => Some(EngineEvent::Title(Some(title))),
            Event::ResetTitle => Some(EngineEvent::Title(None)),
            Event::Bell => Some(EngineEvent::Bell),
            // ClipboardLoad / ColorRequest / TextAreaSizeRequest are
            // permission-gated queries (PLAN.md §5.4): the M2 query policy
            // decides what may be answered; until then they stay
            // unanswered, exactly like a terminal with the feature off.
            _ => None,
        };
        if let Some(event) = mapped {
            self.events
                .lock()
                .expect("engine event queue poisoned")
                .push_back(event);
        }
    }
}

/// One terminal instance: engine state plus its incremental parser.
// The M2-2 runtime integration constructs this outside tests.
#[allow(dead_code)]
pub struct Terminal {
    term: Term<QueueListener>,
    processor: Processor,
    listener: QueueListener,
}

// Methods not yet consumed outside tests are consumed by the M2-2
// runtime integration; until then the bin crate would flag them.
#[allow(dead_code)]
impl Terminal {
    /// A fresh terminal of `rows`×`cols` keeping `scrollback` history lines.
    pub fn new(rows: u16, cols: u16, scrollback: usize) -> Self {
        let config = Config {
            scrolling_history: scrollback,
            ..Config::default()
        };
        let listener = QueueListener::default();
        Self {
            term: Term::new(
                config,
                &TermSize::new(cols.max(1) as usize, rows.max(1) as usize),
                listener.clone(),
            ),
            processor: Processor::new(),
            listener,
        }
    }

    /// Advance the terminal over one raw PTY chunk. Query responses and
    /// other events queue in stream order; drain them with
    /// [`Terminal::drain_events`].
    pub fn feed(&mut self, bytes: &[u8]) {
        self.processor.advance(&mut self.term, bytes);
    }

    /// Events raised since the last drain, in stream order.
    pub fn drain_events(&mut self) -> Vec<EngineEvent> {
        self.listener
            .events
            .lock()
            .expect("engine event queue poisoned")
            .drain(..)
            .collect()
    }

    /// Non-destructive resize with native reflow: logical lines and their
    /// content survive a shrink/widen cycle (PLAN.md §5.3).
    pub fn resize(&mut self, rows: u16, cols: u16) {
        self.term
            .resize(TermSize::new(cols.max(1) as usize, rows.max(1) as usize));
    }

    pub fn modes(&self) -> EngineModes {
        let mode = self.term.mode();
        EngineModes {
            app_cursor_keys: mode.contains(TermMode::APP_CURSOR),
            bracketed_paste: mode.contains(TermMode::BRACKETED_PASTE),
            alt_screen: mode.contains(TermMode::ALT_SCREEN),
        }
    }

    /// Cursor position as (row, column), zero-based, visible screen.
    pub fn cursor_position(&self) -> (u16, u16) {
        let point = self.term.grid().cursor.point;
        (
            point.line.0.clamp(0, i32::from(u16::MAX)) as u16,
            point.column.0.min(usize::from(u16::MAX)) as u16,
        )
    }

    /// Text of one row of the visible screen (`row` zero-based), trailing
    /// blanks trimmed, wide-char spacer cells elided.
    pub fn screen_row_text(&self, row: u16) -> String {
        let grid = self.term.grid();
        if usize::from(row) >= grid.screen_lines() {
            return String::new();
        }
        row_text(&grid[Line(i32::from(row))])
    }

    /// Visible screen rows, top to bottom (length == rows at construction
    /// or last resize).
    pub fn screen_lines(&self) -> Vec<String> {
        let grid = self.term.grid();
        (0..grid.screen_lines())
            .map(|line| row_text(&grid[Line(line as i32)]))
            .collect()
    }

    /// Scrollback + visible rows, oldest first: line indices run from
    /// `-history` to `screen_lines - 1` in engine terms.
    pub fn full_lines(&self) -> Vec<String> {
        let grid = self.term.grid();
        let history = grid.history_size() as i32;
        (-history..grid.screen_lines() as i32)
            .map(|line| row_text(&grid[Line(line)]))
            .collect()
    }

    /// Number of retained scrollback lines.
    pub fn history_size(&self) -> usize {
        self.term.grid().history_size()
    }
}

/// Visible text of one grid row: skip wide-char spacers, stop at the first
/// unwritten cell, trim trailing blanks.
fn row_text(row: &alacritty_terminal::grid::Row<alacritty_terminal::term::cell::Cell>) -> String {
    use alacritty_terminal::term::cell::Flags;
    let mut text = String::new();
    for cell in row.into_iter() {
        if cell
            .flags
            .contains(Flags::WIDE_CHAR_SPACER | Flags::LEADING_WIDE_CHAR_SPACER)
        {
            continue;
        }
        if cell.c == '\0' {
            break;
        }
        text.push(cell.c);
    }
    text.trim_end().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The M0 engine-eval corpus (tools/engine-eval), ported so the main
    /// crate pins clean-stream agreement with the incumbent oracle.
    fn corpus() -> Vec<(&'static str, Vec<u8>)> {
        vec![
            ("plain lines", b"one\r\ntwo\r\nthree\r\n".to_vec()),
            (
                "sgr styles",
                b"\x1b[1;31mred bold\x1b[0m plain\r\n\x1b[4munderline\x1b[0m\r\n".to_vec(),
            ),
            (
                "wrapped long line",
                format!("{}\r\nnext\r\n", "w".repeat(200)).into_bytes(),
            ),
            (
                "scrollback fill",
                (0..40)
                    .map(|i| format!("line {i:03}\r\n"))
                    .collect::<String>()
                    .into_bytes(),
            ),
            (
                "alternate screen roundtrip",
                b"MAIN\r\n\x1b[?1049h\x1b[2J\x1b[HTUI-FRAME\x1b[?1049lMAIN-BACK\r\n".to_vec(),
            ),
            (
                "utf8 multibyte",
                "héllo wörld — ünïcødé ✓\r\n".as_bytes().to_vec(),
            ),
            (
                "mixed modes",
                b"\x1b[?25lhidden-cursor\r\n\x1b[7mrev\x1b[27m normal\r\n\x1b[?25h".to_vec(),
            ),
        ]
    }

    fn vt100_text(rows: u16, cols: u16, stream: &[u8]) -> Vec<String> {
        let mut parser = vt100::Parser::new(rows, cols, 10_000);
        parser.process(stream);
        trim_blank_edges(
            parser
                .screen()
                .contents()
                .lines()
                .map(|l| l.trim_end().to_string())
                .collect(),
        )
    }

    fn trim_blank_edges(mut lines: Vec<String>) -> Vec<String> {
        while lines.last().is_some_and(|l| l.is_empty()) {
            lines.pop();
        }
        while lines.first().is_some_and(|l| l.is_empty()) {
            lines.remove(0);
        }
        lines
    }

    #[test]
    fn clean_stream_corpus_agrees_with_vt100_oracle() {
        for (name, stream) in corpus() {
            let mut term = Terminal::new(24, 80, 10_000);
            term.feed(&stream);
            let ours = trim_blank_edges(term.screen_lines());
            // The wrapped-long-line case is the known API difference from
            // the M0 eval: alacritty keeps one logical (wrapped) row where
            // vt100 reports physical rows. Joining logical continuation is
            // semantics-preserving, so compare the flattened text there.
            let oracle = vt100_text(24, 80, &stream);
            if name == "wrapped long line" {
                assert_eq!(
                    ours.join("").replace("\n", ""),
                    oracle.join("").replace("\n", ""),
                    "{name}: flattened wrapped text must agree"
                );
            } else {
                assert_eq!(ours, oracle, "{name}: visible screen must agree");
            }
        }
    }

    /// The engine-level fix for PLAN.md §5.3 / the ignored
    /// `repro_shrink_then_widen_preserves_history`: history text beyond the
    /// shrunken width must survive a shrink/widen cycle.
    #[test]
    fn shrink_then_widen_preserves_history() {
        let mut term = Terminal::new(6, 80, 1_000);
        let mut lines = String::new();
        for i in 1..=20 {
            lines.push_str(&format!("line {i:02}{}MARKER{i:02}\r\n", "y".repeat(62)));
        }
        term.feed(lines.as_bytes());

        term.resize(6, 40);
        term.resize(6, 80);

        let history = term.full_lines().join("\n");
        for i in 1..=20 {
            assert!(
                history.contains(&format!("MARKER{i:02}")),
                "MARKER{i:02} lost across shrink/widen: {history:?}"
            );
        }
    }

    /// The engine-level fix for PLAN.md I5 / the ignored
    /// `repro_queries_are_answered_at_their_own_stream_position`: each
    /// query is answered at its own stream position, by construction —
    /// and identically when the same stream is split at every byte.
    #[test]
    fn queries_answered_at_exact_stream_position() {
        let stream = b"A\x1b[6nB\x1b[6n";

        let responses = |chunks: &[&[u8]]| {
            let mut term = Terminal::new(24, 80, 0);
            let mut out = Vec::new();
            for chunk in chunks {
                term.feed(chunk);
                out.extend(term.drain_events());
            }
            out
        };

        let whole = responses(&[stream]);
        assert_eq!(
            whole,
            vec![
                EngineEvent::Respond(b"\x1b[1;2R".to_vec()),
                EngineEvent::Respond(b"\x1b[1;3R".to_vec()),
            ],
            "each CPR reports its own position"
        );

        // Split at every byte boundary: identical responses every time.
        for split in 1..stream.len() {
            assert_eq!(
                responses(&[&stream[..split], &stream[split..]]),
                whole,
                "split at byte {split} must not change the answers"
            );
        }
    }

    #[test]
    fn modes_track_engine_flags() {
        let mut term = Terminal::new(24, 80, 0);
        assert_eq!(term.modes(), EngineModes::default());

        term.feed(b"\x1b[?2004h\x1b[?1h");
        let modes = term.modes();
        assert!(modes.bracketed_paste);
        assert!(modes.app_cursor_keys);
        assert!(!modes.alt_screen);

        term.feed(b"\x1b[?1049h");
        assert!(term.modes().alt_screen);
        term.feed(b"\x1b[?2004l\x1b[?1l\x1b[?1049l");
        assert_eq!(term.modes(), EngineModes::default());
    }

    #[test]
    fn alternate_screen_roundtrip_preserves_main_buffer() {
        let mut term = Terminal::new(24, 80, 0);
        term.feed(b"MAIN\r\n");
        term.feed(b"\x1b[?1049h\x1b[2J\x1b[HTUI-FRAME");
        assert!(term.screen_lines().iter().any(|l| l.contains("TUI-FRAME")));
        assert!(!term.screen_lines().iter().any(|l| l.contains("MAIN")));

        term.feed(b"\x1b[?1049lMAIN-BACK\r\n");
        let screen = term.screen_lines().join("\n");
        assert!(screen.contains("MAIN"), "main buffer restored: {screen:?}");
        assert!(screen.contains("MAIN-BACK"));
        assert!(!screen.contains("TUI-FRAME"));
    }

    #[test]
    fn title_and_bell_events_surface() {
        let mut term = Terminal::new(24, 80, 0);
        term.feed(b"\x1b]2;my title\x07\x07");
        assert_eq!(
            term.drain_events(),
            vec![
                EngineEvent::Title(Some("my title".to_string())),
                EngineEvent::Bell,
            ]
        );
    }

    #[test]
    fn cursor_position_tracks_output() {
        let mut term = Terminal::new(24, 80, 0);
        assert_eq!(term.cursor_position(), (0, 0));
        term.feed(b"hello");
        assert_eq!(term.cursor_position(), (0, 5));
        term.feed(b"\r\nworld");
        assert_eq!(term.cursor_position(), (1, 5));
    }
}
