//! Terminal engine adapter (ADR-0001): the narrow seam between oly and the
//! embedded terminal core (`alacritty_terminal` 0.26).
//!
//! The rest of the codebase must not depend on engine types directly —
//! session state, snapshots, mode tracking, and query answering all go
//! through [`Terminal`]. The engine owns terminal semantics; oly owns
//! ordering (one feed per journal-sequenced chunk, under the session write
//! lock), policy (which queries may be answered), and persistence.
//!
//! Query responses are generated by the engine *while* a chunk advances,
//! i.e. at the exact stream position of each query (invariant I5) — a
//! chunk containing `A`, CPR, `B`, CPR yields two responses with two
//! distinct cursor positions, by construction.

use std::collections::VecDeque;
use std::sync::{Arc, Mutex};

use alacritty_terminal::event::{Event, EventListener};
use alacritty_terminal::grid::Dimensions;
use alacritty_terminal::index::Line;
use alacritty_terminal::term::cell::{Cell, Flags};
use alacritty_terminal::term::{Config, Term, TermMode, test::TermSize};
use alacritty_terminal::vte::ansi::{Color, NamedColor, Processor, Rgb};

/// Events the engine raised while feeding one chunk, in stream order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EngineEvent {
    /// Bytes the terminal asks to be written back to the PTY (query
    /// response: CPR/DSR/DA/DECRQM/…). Generated at the query's exact
    /// position in the stream; writing them in drain order preserves it.
    Respond(Vec<u8>),
    /// Window title set (OSC 0/2) or reset to default (`None`).
    Title(Option<String>),
    /// BEL received.
    Bell,
}

/// Terminal modes oly's input translation and attach relays track.
// The M2-2 runtime integration constructs this outside tests.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct EngineModes {
    pub app_cursor_keys: bool,
    pub bracketed_paste: bool,
    pub alt_screen: bool,
    /// Any mouse reporting mode (1000/1002/1003).
    pub mouse_report: bool,
    /// SGR (1006) mouse encoding negotiated; otherwise legacy X11
    /// encoding applies.
    pub sgr_mouse: bool,
    /// Focus in/out reporting (1004).
    pub focus_events: bool,
}

/// The colours the engine reports for `OSC 10 ; ?` / `OSC 11 ; ?` probes.
///
/// Defaults to the conservative white-on-black pair the pre-engine daemon
/// answered with; the daemon overrides it from the environment (COLORFGBG)
/// at session spawn. Palette-index colour queries (`OSC 4 ; .. ; ?`) stay
/// unanswered, matching the pre-engine behaviour.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ReportColors {
    pub foreground: Rgb,
    pub background: Rgb,
}

impl Default for ReportColors {
    fn default() -> Self {
        Self {
            foreground: Rgb {
                r: 0xff,
                g: 0xff,
                b: 0xff,
            },
            background: Rgb { r: 0, g: 0, b: 0 },
        }
    }
}

/// Listener handed to `Term`; events fired during `advance` are queued and
/// drained by the adapter after the feed returns.
#[derive(Clone, Default)]
struct QueueListener {
    events: Arc<Mutex<VecDeque<EngineEvent>>>,
    colors: Arc<Mutex<ReportColors>>,
}

impl EventListener for QueueListener {
    fn send_event(&self, event: Event) {
        let mapped = match event {
            Event::PtyWrite(text) => Some(EngineEvent::Respond(text.into_bytes())),
            Event::Title(title) => Some(EngineEvent::Title(Some(title))),
            Event::ResetTitle => Some(EngineEvent::Title(None)),
            Event::Bell => Some(EngineEvent::Bell),
            Event::ColorRequest(index, formatter) => {
                // Foreground/background probes are answered with the
                // daemon's configured colours; the engine formats the reply
                // with the query's own terminator, and the event fires while
                // the chunk is consumed, so the reply lands at the query's
                // exact stream position — interleaved correctly with DA/CPR
                // replies (PLAN.md §5.1/I5).
                let colors = *self.colors.lock().expect("report colors poisoned");
                let color = match index {
                    i if i == NamedColor::Foreground as usize => Some(colors.foreground),
                    i if i == NamedColor::Background as usize => Some(colors.background),
                    // Palette-index queries stay unanswered, as pre-M2.
                    _ => None,
                };
                color.map(|c| EngineEvent::Respond(formatter(c).into_bytes()))
            }
            // ClipboardLoad / TextAreaSizeRequest are permission-gated
            // queries (PLAN.md §5.4): they stay unanswered, exactly like a
            // terminal with the feature off.
            _ => None,
        };
        if let Some(event) = mapped {
            self.events
                .lock()
                .expect("engine event queue poisoned")
                .push_back(event);
        }
    }
}

/// One terminal instance: engine state plus its incremental parser.
// The M2-2 runtime integration constructs this outside tests.
#[allow(dead_code)]
pub struct Terminal {
    term: Term<QueueListener>,
    processor: Processor,
    listener: QueueListener,
    report_colors: Arc<Mutex<ReportColors>>,
}

// Methods not yet consumed outside tests are consumed by the M2-2
// runtime integration; until then the bin crate would flag them.
#[allow(dead_code)]
impl Terminal {
    /// A fresh terminal of `rows`×`cols` keeping `scrollback` history lines.
    pub fn new(rows: u16, cols: u16, scrollback: usize) -> Self {
        let config = Config {
            scrolling_history: scrollback,
            ..Config::default()
        };
        let report_colors = Arc::new(Mutex::new(ReportColors::default()));
        let listener = QueueListener {
            colors: report_colors.clone(),
            ..QueueListener::default()
        };
        Self {
            term: Term::new(
                config,
                &TermSize::new(cols.max(1) as usize, rows.max(1) as usize),
                listener.clone(),
            ),
            processor: Processor::new(),
            listener,
            report_colors,
        }
    }

    /// Set the colours reported for `OSC 10 ; ?` / `OSC 11 ; ?` probes.
    pub fn set_report_colors(&mut self, colors: ReportColors) {
        *self.report_colors.lock().expect("report colors poisoned") = colors;
    }

    /// Advance the terminal over one raw PTY chunk. Query responses and
    /// other events queue in stream order; drain them with
    /// [`Terminal::drain_events`].
    pub fn feed(&mut self, bytes: &[u8]) {
        self.processor.advance(&mut self.term, bytes);
    }

    /// Events raised since the last drain, in stream order.
    pub fn drain_events(&mut self) -> Vec<EngineEvent> {
        self.listener
            .events
            .lock()
            .expect("engine event queue poisoned")
            .drain(..)
            .collect()
    }

    /// Non-destructive resize with native reflow: logical lines and their
    /// content survive a shrink/widen cycle (PLAN.md §5.3).
    pub fn resize(&mut self, rows: u16, cols: u16) {
        self.term
            .resize(TermSize::new(cols.max(1) as usize, rows.max(1) as usize));
    }

    pub fn modes(&self) -> EngineModes {
        let mode = self.term.mode();
        EngineModes {
            app_cursor_keys: mode.contains(TermMode::APP_CURSOR),
            bracketed_paste: mode.contains(TermMode::BRACKETED_PASTE),
            alt_screen: mode.contains(TermMode::ALT_SCREEN),
            mouse_report: mode.intersects(TermMode::MOUSE_MODE),
            sgr_mouse: mode.contains(TermMode::SGR_MOUSE),
            focus_events: mode.contains(TermMode::FOCUS_IN_OUT),
        }
    }

    /// Cursor position as (row, column), zero-based, visible screen.
    /// Current geometry as (rows, cols).
    pub fn size(&self) -> (u16, u16) {
        (
            self.term.grid().screen_lines().max(1) as u16,
            self.term.grid().columns().max(1) as u16,
        )
    }

    /// Current cursor as zero-based (row, col) on the visible screen.
    pub fn cursor_position(&self) -> (u16, u16) {
        let point = self.term.grid().cursor.point;
        (
            point.line.0.clamp(0, i32::from(u16::MAX)) as u16,
            point.column.0.min(usize::from(u16::MAX)) as u16,
        )
    }

    /// Whether the cursor is visible (DECTCEM).
    pub fn cursor_visible(&self) -> bool {
        self.term.mode().contains(TermMode::SHOW_CURSOR)
    }

    /// Text of one row of the visible screen (`row` zero-based), trailing
    /// blanks trimmed, wide-char spacer cells elided.
    pub fn screen_row_text(&self, row: u16) -> String {
        let grid = self.term.grid();
        if usize::from(row) >= grid.screen_lines() {
            return String::new();
        }
        row_text(&grid[Line(i32::from(row))])
    }

    /// Visible screen rows, top to bottom (length == rows at construction
    /// or last resize).
    pub fn screen_lines(&self) -> Vec<String> {
        let grid = self.term.grid();
        (0..grid.screen_lines())
            .map(|line| row_text(&grid[Line(line as i32)]))
            .collect()
    }

    /// Scrollback + visible rows, oldest first: line indices run from
    /// `-history` to `screen_lines - 1` in engine terms.
    pub fn full_lines(&self) -> Vec<String> {
        let grid = self.term.grid();
        let history = grid.history_size() as i32;
        (-history..grid.screen_lines() as i32)
            .map(|line| row_text(&grid[Line(line)]))
            .collect()
    }

    /// Number of retained scrollback lines.
    pub fn history_size(&self) -> usize {
        self.term.grid().history_size()
    }

    /// Styled visible rows (SGR-encoded, trailing blanks trimmed), top to
    /// bottom. This is the renderer restore adapter's row source: engine
    /// state rendered into a plain xterm-compatible byte stream.
    pub fn styled_screen_rows(&self) -> Vec<Vec<u8>> {
        let grid = self.term.grid();
        (0..grid.screen_lines())
            .map(|line| styled_row(&grid[Line(line as i32)]))
            .collect()
    }

    /// Styled scrollback rows (oldest first, newest last), limited to the
    /// newest `tail` retained rows. Excludes the visible screen.
    pub fn styled_history_rows(&self, tail: usize) -> Vec<Vec<u8>> {
        let grid = self.term.grid();
        let history = grid.history_size();
        let start = history.saturating_sub(tail);
        (start..history)
            .map(|h| styled_row(&grid[Line(-(history as i32) + h as i32)]))
            .collect()
    }

    /// Renderer restoration stream (ADR-0001 #4): a fresh xterm-compatible
    /// parser fed these bytes displays the current visible screen — clear,
    /// styled rows, SGR reset, cursor position and visibility. Deliberately
    /// a *renderer* artifact, not an engine checkpoint: parser fragments,
    /// wrap-pending and mode stacks are not encoded (the M3 checkpoint
    /// covers exact continuation).
    pub fn snapshot_stream(&self) -> Vec<u8> {
        let mut out = Vec::new();
        // Home + erase below (and the scrollback purge): the attaching
        // client's current screen is replaced, not appended to.
        out.extend_from_slice(b"\x1b[H\x1b[2J");
        let rows = self.styled_screen_rows();
        for (index, row) in rows.iter().enumerate() {
            if index > 0 {
                out.extend_from_slice(b"\r\n");
            }
            out.extend_from_slice(row);
        }
        out.extend_from_slice(b"\x1b[0m");
        let (row, col) = self.cursor_position();
        out.extend_from_slice(format!("\x1b[{};{}H", row + 1, col + 1).as_bytes());
        out.extend_from_slice(if self.term.mode().contains(TermMode::SHOW_CURSOR) {
            b"\x1b[?25h"
        } else {
            b"\x1b[?25l"
        });
        out
    }
}

/// SGR-encode one grid row: runs of cells with identical rendition become
/// one SGR sequence plus text; trailing unwritten cells are trimmed and
/// wide-char spacers are elided (their leading cell already emitted the
/// glyph).
fn styled_row(row: &alacritty_terminal::grid::Row<Cell>) -> Vec<u8> {
    #[derive(Clone, Copy, PartialEq, Eq)]
    struct Rendition {
        fg: Color,
        bg: Color,
        attrs: Flags,
    }

    const ATTRS: Flags = Flags::from_bits_retain(
        Flags::BOLD.bits()
            | Flags::DIM.bits()
            | Flags::ITALIC.bits()
            | Flags::UNDERLINE.bits()
            | Flags::INVERSE.bits()
            | Flags::STRIKEOUT.bits()
            | Flags::HIDDEN.bits(),
    );

    let default = Rendition {
        fg: Color::Named(NamedColor::Foreground),
        bg: Color::Named(NamedColor::Background),
        attrs: Flags::empty(),
    };
    let mut out = Vec::new();
    // Rows are concatenated after a reset, so the parser starts each row in
    // the default rendition; default runs emit no SGR at all.
    let mut current = Some(default);
    // End of the last cell that carries visible content; trailing
    // default-rendition blanks are padding and are trimmed off.
    let mut content_end = 0;
    let mut reset_needed_at_end = false;
    for cell in row.into_iter() {
        if cell
            .flags
            .intersects(Flags::WIDE_CHAR_SPACER | Flags::LEADING_WIDE_CHAR_SPACER)
        {
            continue;
        }
        let next = Rendition {
            fg: cell.fg,
            bg: cell.bg,
            attrs: cell.flags & ATTRS,
        };
        if current != Some(next) {
            write_sgr(&mut out, next.fg, next.bg, next.attrs);
            current = Some(next);
        }
        out.extend_from_slice(cell.c.encode_utf8(&mut [0u8; 4]).as_bytes());
        let visible_blank = cell.c == ' '
            && next.bg == Color::Named(NamedColor::Background)
            && next.attrs.is_empty();
        if !visible_blank {
            content_end = out.len();
            reset_needed_at_end = current != Some(default);
        }
    }
    out.truncate(content_end);
    // Never emit trailing SGR state: a plain reset closes the row.
    if reset_needed_at_end {
        out.extend_from_slice(b"\x1b[0m");
    }
    out
}

fn write_sgr(out: &mut Vec<u8>, fg: Color, bg: Color, attrs: Flags) {
    let mut codes: Vec<String> = vec!["0".to_string()];
    if attrs.contains(Flags::BOLD) {
        codes.push("1".into());
    }
    if attrs.contains(Flags::DIM) {
        codes.push("2".into());
    }
    if attrs.contains(Flags::ITALIC) {
        codes.push("3".into());
    }
    if attrs.contains(Flags::UNDERLINE) {
        codes.push("4".into());
    }
    if attrs.contains(Flags::INVERSE) {
        codes.push("7".into());
    }
    if attrs.contains(Flags::HIDDEN) {
        codes.push("8".into());
    }
    if attrs.contains(Flags::STRIKEOUT) {
        codes.push("9".into());
    }
    push_color(&mut codes, fg, false);
    push_color(&mut codes, bg, true);
    out.extend_from_slice(format!("\x1b[{}m", codes.join(";")).as_bytes());
}

fn push_color(codes: &mut Vec<String>, color: Color, background: bool) {
    let (base, bright_base) = if background { (40, 100) } else { (30, 90) };
    match color {
        Color::Spec(rgb) => codes.push(format!(
            "{};2;{};{};{}",
            if background { 48 } else { 38 },
            rgb.r,
            rgb.g,
            rgb.b
        )),
        Color::Indexed(index) => {
            codes.push(format!("{};5;{}", if background { 48 } else { 38 }, index))
        }
        Color::Named(named) => {
            let value = named as usize;
            if value < 8 {
                codes.push(format!("{}", base + value));
            } else if value < 16 {
                codes.push(format!("{}", bright_base + value - 8));
            } else if (NamedColor::DimBlack as usize..=NamedColor::DimWhite as usize)
                .contains(&value)
            {
                codes.push("2".into());
                codes.push(format!("{}", base + value - NamedColor::DimBlack as usize));
            }
            // Foreground/Background/Cursor (and anything unknown) map to the
            // terminal default — no code needed after the reset.
        }
    }
}

/// Visible text of one grid row: skip wide-char spacers, stop at the first
/// unwritten cell, trim trailing blanks.
fn row_text(row: &alacritty_terminal::grid::Row<alacritty_terminal::term::cell::Cell>) -> String {
    use alacritty_terminal::term::cell::Flags;
    let mut text = String::new();
    for cell in row.into_iter() {
        if cell
            .flags
            .intersects(Flags::WIDE_CHAR_SPACER | Flags::LEADING_WIDE_CHAR_SPACER)
        {
            continue;
        }
        if cell.c == '\0' {
            break;
        }
        text.push(cell.c);
    }
    text.trim_end().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The engine-selection corpus (ADR-0001), pinned so the main crate
    /// keeps clean-stream agreement with the incumbent oracle.
    fn corpus() -> Vec<(&'static str, Vec<u8>)> {
        vec![
            ("plain lines", b"one\r\ntwo\r\nthree\r\n".to_vec()),
            (
                "sgr styles",
                b"\x1b[1;31mred bold\x1b[0m plain\r\n\x1b[4munderline\x1b[0m\r\n".to_vec(),
            ),
            (
                "wrapped long line",
                format!("{}\r\nnext\r\n", "w".repeat(200)).into_bytes(),
            ),
            (
                "scrollback fill",
                (0..40)
                    .map(|i| format!("line {i:03}\r\n"))
                    .collect::<String>()
                    .into_bytes(),
            ),
            (
                "alternate screen roundtrip",
                b"MAIN\r\n\x1b[?1049h\x1b[2J\x1b[HTUI-FRAME\x1b[?1049lMAIN-BACK\r\n".to_vec(),
            ),
            (
                "utf8 multibyte",
                "héllo wörld — ünïcødé ✓\r\n".as_bytes().to_vec(),
            ),
            (
                "mixed modes",
                b"\x1b[?25lhidden-cursor\r\n\x1b[7mrev\x1b[27m normal\r\n\x1b[?25h".to_vec(),
            ),
        ]
    }

    fn vt100_text(rows: u16, cols: u16, stream: &[u8]) -> Vec<String> {
        let mut parser = vt100::Parser::new(rows, cols, 10_000);
        parser.process(stream);
        trim_blank_edges(
            parser
                .screen()
                .contents()
                .lines()
                .map(|l| l.trim_end().to_string())
                .collect(),
        )
    }

    fn trim_blank_edges(mut lines: Vec<String>) -> Vec<String> {
        while lines.last().is_some_and(|l| l.is_empty()) {
            lines.pop();
        }
        while lines.first().is_some_and(|l| l.is_empty()) {
            lines.remove(0);
        }
        lines
    }

    #[test]
    fn clean_stream_corpus_agrees_with_vt100_oracle() {
        for (name, stream) in corpus() {
            let mut term = Terminal::new(24, 80, 10_000);
            term.feed(&stream);
            let ours = trim_blank_edges(term.screen_lines());
            // The wrapped-long-line case is the known API difference from
            // the M0 eval: alacritty keeps one logical (wrapped) row where
            // vt100 reports physical rows. Joining logical continuation is
            // semantics-preserving, so compare the flattened text there.
            let oracle = vt100_text(24, 80, &stream);
            if name == "wrapped long line" {
                assert_eq!(
                    ours.join("").replace("\n", ""),
                    oracle.join("").replace("\n", ""),
                    "{name}: flattened wrapped text must agree"
                );
            } else {
                assert_eq!(ours, oracle, "{name}: visible screen must agree");
            }
        }
    }

    /// The engine-level fix for PLAN.md §5.3 / the ignored
    /// `repro_shrink_then_widen_preserves_history`: history text beyond the
    /// shrunken width must survive a shrink/widen cycle.
    #[test]
    fn shrink_then_widen_preserves_history() {
        let mut term = Terminal::new(6, 80, 1_000);
        let mut lines = String::new();
        for i in 1..=20 {
            lines.push_str(&format!("line {i:02}{}MARKER{i:02}\r\n", "y".repeat(62)));
        }
        term.feed(lines.as_bytes());

        term.resize(6, 40);
        term.resize(6, 80);

        let history = term.full_lines().join("\n");
        for i in 1..=20 {
            assert!(
                history.contains(&format!("MARKER{i:02}")),
                "MARKER{i:02} lost across shrink/widen: {history:?}"
            );
        }
    }

    /// The `Respond` payloads raised by feeding `bytes` in one chunk.
    fn responses(bytes: &[u8]) -> Vec<Vec<u8>> {
        let mut term = Terminal::new(24, 80, 100);
        term.feed(bytes);
        term.drain_events()
            .into_iter()
            .filter_map(|event| match event {
                EngineEvent::Respond(bytes) => Some(bytes),
                _ => None,
            })
            .collect()
    }

    /// I5 across query kinds: DA, OSC colour probes, and CPR in one chunk
    /// are answered in the order they appear in the stream. A colour-detect
    /// helper that reads replies until the DA sentinel (e.g. termbg /
    /// terminal-light, used by real TUIs) breaks if the DA reply overtakes
    /// the colour replies it precedes.
    #[test]
    fn mixed_queries_answer_in_stream_order() {
        let stream = b"\x1b]10;?\x07\x1b]11;?\x1b\\\x1b[cA\x1b[6n\x1b[5n";
        assert_eq!(
            responses(stream),
            vec![
                b"\x1b]10;rgb:ffff/ffff/ffff\x07".to_vec(),
                b"\x1b]11;rgb:0000/0000/0000\x1b\\".to_vec(),
                b"\x1b[?6c".to_vec(),
                b"\x1b[1;2R".to_vec(),
                b"\x1b[0n".to_vec(),
            ],
            "every reply at its own stream position, in stream order"
        );
    }

    /// The reported colours are configurable (the daemon derives them from
    /// the COLORFGBG environment at session spawn).
    #[test]
    fn colour_queries_use_configured_report_colors() {
        let mut term = Terminal::new(24, 80, 100);
        term.set_report_colors(ReportColors {
            foreground: Rgb {
                r: 0x11,
                g: 0x22,
                b: 0x33,
            },
            background: Rgb {
                r: 0x44,
                g: 0x55,
                b: 0x66,
            },
        });
        term.feed(b"\x1b]10;?\x07\x1b]11;?\x07");
        let responses: Vec<Vec<u8>> = term
            .drain_events()
            .into_iter()
            .filter_map(|event| match event {
                EngineEvent::Respond(bytes) => Some(bytes),
                _ => None,
            })
            .collect();
        assert_eq!(
            responses,
            vec![
                b"\x1b]10;rgb:1111/2222/3333\x07".to_vec(),
                b"\x1b]11;rgb:4444/5555/6666\x07".to_vec(),
            ]
        );
    }

    /// Palette-index colour queries stay unanswered (pre-M2 parity): the
    /// session only ever answered foreground/background probes.
    #[test]
    fn palette_colour_queries_stay_unanswered() {
        assert!(responses(b"\x1b]4;1;?\x07").is_empty());
    }

    /// The engine-level fix for PLAN.md I5 / the ignored
    /// `repro_queries_are_answered_at_their_own_stream_position`: each
    /// query is answered at its own stream position, by construction —
    /// and identically when the same stream is split at every byte.
    #[test]
    fn queries_answered_at_exact_stream_position() {
        let stream = b"A\x1b[6nB\x1b[6n";

        let responses = |chunks: &[&[u8]]| {
            let mut term = Terminal::new(24, 80, 0);
            let mut out = Vec::new();
            for chunk in chunks {
                term.feed(chunk);
                out.extend(term.drain_events());
            }
            out
        };

        let whole = responses(&[stream]);
        assert_eq!(
            whole,
            vec![
                EngineEvent::Respond(b"\x1b[1;2R".to_vec()),
                EngineEvent::Respond(b"\x1b[1;3R".to_vec()),
            ],
            "each CPR reports its own position"
        );

        // Split at every byte boundary: identical responses every time.
        for split in 1..stream.len() {
            assert_eq!(
                responses(&[&stream[..split], &stream[split..]]),
                whole,
                "split at byte {split} must not change the answers"
            );
        }
    }

    #[test]
    fn modes_track_engine_flags() {
        let mut term = Terminal::new(24, 80, 0);
        assert_eq!(term.modes(), EngineModes::default());

        term.feed(b"\x1b[?2004h\x1b[?1h");
        let modes = term.modes();
        assert!(modes.bracketed_paste);
        assert!(modes.app_cursor_keys);
        assert!(!modes.alt_screen);

        term.feed(b"\x1b[?1049h");
        assert!(term.modes().alt_screen);
        term.feed(b"\x1b[?2004l\x1b[?1l\x1b[?1049l");
        assert_eq!(term.modes(), EngineModes::default());

        // Mouse and focus reporting modes are tracked for attach clients.
        term.feed(b"\x1b[?1002h\x1b[?1006h\x1b[?1004h");
        let modes = term.modes();
        assert!(modes.mouse_report);
        assert!(modes.sgr_mouse);
        assert!(modes.focus_events);
        term.feed(b"\x1b[?1002l\x1b[?1006l\x1b[?1004l");
        assert_eq!(term.modes(), EngineModes::default());
    }

    #[test]
    fn alternate_screen_roundtrip_preserves_main_buffer() {
        let mut term = Terminal::new(24, 80, 0);
        term.feed(b"MAIN\r\n");
        term.feed(b"\x1b[?1049h\x1b[2J\x1b[HTUI-FRAME");
        assert!(term.screen_lines().iter().any(|l| l.contains("TUI-FRAME")));
        assert!(!term.screen_lines().iter().any(|l| l.contains("MAIN")));

        term.feed(b"\x1b[?1049lMAIN-BACK\r\n");
        let screen = term.screen_lines().join("\n");
        assert!(screen.contains("MAIN"), "main buffer restored: {screen:?}");
        assert!(screen.contains("MAIN-BACK"));
        assert!(!screen.contains("TUI-FRAME"));
    }

    #[test]
    fn title_and_bell_events_surface() {
        let mut term = Terminal::new(24, 80, 0);
        term.feed(b"\x1b]2;my title\x07\x07");
        assert_eq!(
            term.drain_events(),
            vec![
                EngineEvent::Title(Some("my title".to_string())),
                EngineEvent::Bell,
            ]
        );
    }

    #[test]
    fn snapshot_stream_restores_cjk_wide_chars_in_a_fresh_parser() {
        // CJK glyphs occupy two grid cells; the snapshot must reproduce them
        // exactly (no extra/missing spacer) in a fresh client parser.
        let mut term = Terminal::new(6, 40, 100);
        term.feed("中文字符串测试 hello\r\n│你好│ world\r\n末尾宽字符对齐测试ABC".as_bytes());

        let snapshot = term.snapshot_stream();
        let mut client = vt100::Parser::new(6, 40, 0);
        client.process(&snapshot);
        let restored: Vec<String> = client
            .screen()
            .contents()
            .lines()
            .map(|l| l.trim_end().to_string())
            .collect();
        // Pin the exact text, not just self-agreement: a renderer that emits
        // wide-char spacer cells as real spaces used to pass the
        // self-comparison while corrupting every CJK glyph run.
        assert_eq!(
            trim_blank_edges(restored),
            vec![
                "中文字符串测试 hello".to_string(),
                "│你好│ world".to_string(),
                "末尾宽字符对齐测试ABC".to_string()
            ],
            "snapshot restores CJK text exactly; snapshot bytes: {}",
            String::from_utf8_lossy(&snapshot)
        );
        assert_eq!(
            trim_blank_edges(term.screen_lines()),
            vec![
                "中文字符串测试 hello".to_string(),
                "│你好│ world".to_string(),
                "末尾宽字符对齐测试ABC".to_string()
            ],
            "row text keeps CJK runs free of spacer cells"
        );
    }

    #[test]
    fn cup_positioned_wide_chars_render_without_spacer_gaps() {
        // ratatui/codex-style drawing: each wide char is written at an
        // explicit cursor position two columns apart. The grid stores a
        // WIDE_CHAR_SPACER after every glyph; row rendering must elide those
        // spacers (they are not spaces) or every CJK run gains phantom gaps.
        let mut term = Terminal::new(6, 40, 100);
        term.feed("❯ ".as_bytes());
        for (i, ch) in "请用一句中文".chars().enumerate() {
            let col = 3 + i * 2; // 1-based CUP column, wide-char pitch
            term.feed(format!("\x1b[1;{col}H{ch}").as_bytes());
        }
        assert_eq!(term.screen_lines()[0].trim_end(), "❯ 请用一句中文");
        let snapshot = term.snapshot_stream();
        let mut client = vt100::Parser::new(6, 40, 0);
        client.process(&snapshot);
        assert_eq!(
            client
                .screen()
                .contents()
                .lines()
                .next()
                .unwrap()
                .trim_end(),
            "❯ 请用一句中文",
            "snapshot bytes: {}",
            String::from_utf8_lossy(&snapshot)
        );
    }

    #[test]
    fn snapshot_stream_restores_screen_in_a_fresh_parser() {
        let mut term = Terminal::new(6, 40, 100);
        term.feed(b"plain\r\n\x1b[1;31mred bold\x1b[0m\r\n\x1b[?25lhidden cursor");

        // A fresh xterm-ish client (vt100 as the oracle renderer) fed the
        // snapshot must show the same visible text.
        let snapshot = term.snapshot_stream();
        let mut client = vt100::Parser::new(6, 40, 0);
        client.process(&snapshot);
        let restored: Vec<String> = client
            .screen()
            .contents()
            .lines()
            .map(|l| l.trim_end().to_string())
            .collect();
        assert_eq!(
            trim_blank_edges(restored),
            trim_blank_edges(term.screen_lines()),
            "snapshot restores the visible text"
        );
        // Styling is encoded and cursor state restored.
        let text = String::from_utf8_lossy(&snapshot);
        assert!(text.contains("\x1b[0;1;31m"), "bold red run: {text:?}");
        assert!(text.ends_with("\x1b[?25l"), "cursor hidden: {text:?}");
        assert_eq!(
            client.screen().cursor_position(),
            term.cursor_position(),
            "cursor lands at the engine position"
        );
    }

    #[test]
    fn styled_history_rows_returns_newest_tail_only() {
        let mut term = Terminal::new(3, 20, 100);
        let stream: Vec<u8> = (0..10)
            .map(|i| format!("row {i:02}\r\n"))
            .collect::<String>()
            .into_bytes();
        term.feed(&stream);
        let tail = term.styled_history_rows(3);
        let text: Vec<String> = tail
            .iter()
            .map(|r| String::from_utf8_lossy(r).into_owned())
            .collect();
        assert_eq!(text, vec!["row 05", "row 06", "row 07"]);
    }

    #[test]
    fn cursor_position_tracks_output() {
        let mut term = Terminal::new(24, 80, 0);
        assert_eq!(term.cursor_position(), (0, 0));
        term.feed(b"hello");
        assert_eq!(term.cursor_position(), (0, 5));
        term.feed(b"\r\nworld");
        assert_eq!(term.cursor_position(), (1, 5));
    }
}
